volumes:
  venv:

services:
    lamp_reproduce:
        build:
            context: .
            dockerfile: Dockerfile
        image: lamp_reproduce
        volumes:
          - type: bind
            source: .
            target: /app
          - venv:/app/.venv
          - venv:/app/.cache
        environment:
          NVIDIA_VISIBLE_DEVICES: all
          NVIDIA_DRIVER_CAPABILITIES: all
        deploy:
          resources:
            reservations:
              devices:
                - capabilities:
                    - gpu
        command: tail -f /dev/null
        container_name: lamp_reproduce
